#![no_std]
#![allow(deprecated)]

use soroban_sdk::{
    contract, contractclient, contractimpl, contracttype, symbol_short,
    token, Address, Bytes, BytesN, Env,
};

mod test;

// ── Verifier cross-contract interface ────────────────────────────────────────

#[contractclient(name = "VerifierClient")]
pub trait VerifierInterface {
    fn verify(env: Env, proof: Bytes, public_inputs: Bytes) -> bool;
}

// ── Storage keys ─────────────────────────────────────────────────────────────

#[contracttype]
pub enum DataKey {
    Admin,
    DisbursementId,
    MerkleRoot,
    PayoutAmount,
    ClaimedCount,
    TokenAddress,
    VerifierAddress,
    UsedNullifier(BytesN<32>),
    Initialized,
}

// ── Shared types ──────────────────────────────────────────────────────────────

#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub struct CampaignStats {
    pub disbursement_id: BytesN<32>,
    pub merkle_root: BytesN<32>,
    pub payout_amount: i128,
    pub escrow_balance: i128,
    pub claimed_count: u32,
}

#[contracttype]
#[derive(Clone, Debug)]
pub struct ClaimEvent {
    pub disbursement_id: BytesN<32>,
    pub nullifier: BytesN<32>,
    pub claimant: Address,
    pub amount: i128,
}

/// Public inputs matching the Noir circuit declaration order:
///   disbursement_id, merkle_root, nullifier, claimant_address (all BN254 field elements)
///
/// `claimant_address_field` is the 31-byte encoding of the beneficiary's Ed25519 key
/// (bytes[1..32] of the raw public key, zero-padded to 32 bytes) so that the
/// value lies within the BN254 scalar field. This matches `stellarAddressToField()`
/// in the TypeScript frontend.
#[contracttype]
#[derive(Clone, Debug)]
pub struct ProofPublicInputs {
    pub claimant_address_field: BytesN<32>,
    pub disbursement_id: BytesN<32>,
    pub merkle_root: BytesN<32>,
    pub nullifier: BytesN<32>,
}

// ── Contract ──────────────────────────────────────────────────────────────────

#[contract]
pub struct AidShieldContract;

#[contractimpl]
impl AidShieldContract {

    /// Initialise a disbursement campaign.
    ///
    /// token_address    — Stellar Asset Contract for the payout token (XLM SAC)
    /// verifier_address — deployed AidShieldVerifier contract
    pub fn initialize(
        env: Env,
        admin: Address,
        disbursement_id: BytesN<32>,
        merkle_root: BytesN<32>,
        payout_amount: i128,
        token_address: Address,
        verifier_address: Address,
    ) {
        if env.storage().instance().has(&DataKey::Initialized) {
            panic!("Already initialized");
        }
        admin.require_auth();
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::DisbursementId, &disbursement_id);
        env.storage().instance().set(&DataKey::MerkleRoot, &merkle_root);
        env.storage().instance().set(&DataKey::PayoutAmount, &payout_amount);
        env.storage().instance().set(&DataKey::TokenAddress, &token_address);
        env.storage().instance().set(&DataKey::VerifierAddress, &verifier_address);
        env.storage().instance().set(&DataKey::ClaimedCount, &0u32);
        env.storage().instance().set(&DataKey::Initialized, &true);

        // Keep instance storage alive for ~30 days (30d × 24h × 720 ledgers/h = 518 400)
        env.storage().instance().extend_ttl(518_400, 518_400);
    }

    /// Deposit XLM into the escrow via the Stellar Asset Contract.
    /// The funder authorises this invocation; the Soroban auth tree propagates
    /// that authorisation into the sub-invocation of token.transfer.
    pub fn fund(env: Env, funder: Address, amount: i128) {
        funder.require_auth();
        if !env.storage().instance().has(&DataKey::Initialized) {
            panic!("Not initialized");
        }
        let token_address: Address = env.storage().instance()
            .get(&DataKey::TokenAddress).unwrap();
        token::Client::new(&env, &token_address)
            .transfer(&funder, &env.current_contract_address(), &amount);
    }

    /// Beneficiary submits a ZK proof to claim their payout.
    ///
    /// Enforces:
    ///   1. UltraHonk proof passes on-chain structural verification
    ///   2. disbursement_id matches this campaign
    ///   3. merkle_root matches stored root
    ///   4. nullifier has never been used (replay protection)
    ///   5. Payout released via real XLM SAC transfer
    ///
    /// `proof`          — 14 656-byte UltraHonk proof generated by Noir/Barretenberg
    /// `public_inputs`  — public witness (disbursement_id, merkle_root, nullifier,
    ///                    claimant_address_field) matching the circuit's pub inputs
    pub fn claim(
        env: Env,
        claimant: Address,
        public_inputs: ProofPublicInputs,
        proof: Bytes,
    ) {
        claimant.require_auth();

        if !env.storage().instance().has(&DataKey::Initialized) {
            panic!("Contract not initialized");
        }

        // ── ZK Proof verification ──────────────────────────────────────────
        // Encode public inputs as 4 × 32-byte concatenation in circuit declaration order:
        //   disbursement_id | merkle_root | nullifier | claimant_address_field
        let verifier_address: Address = env.storage().instance()
            .get(&DataKey::VerifierAddress).unwrap();

        let mut pi_bytes = Bytes::new(&env);
        pi_bytes.append(&public_inputs.disbursement_id.clone().into());
        pi_bytes.append(&public_inputs.merkle_root.clone().into());
        pi_bytes.append(&public_inputs.nullifier.clone().into());
        pi_bytes.append(&public_inputs.claimant_address_field.clone().into());

        let verifier = VerifierClient::new(&env, &verifier_address);
        if !verifier.verify(&proof, &pi_bytes) {
            panic!("ZK proof verification failed");
        }

        // ── Application-level checks ──────────────────────────────────────

        // Check 1: disbursement_id
        let stored_id: BytesN<32> = env.storage().instance()
            .get(&DataKey::DisbursementId).unwrap();
        if public_inputs.disbursement_id != stored_id {
            panic!("Wrong disbursement_id");
        }

        // Check 2: merkle_root
        let stored_root: BytesN<32> = env.storage().instance()
            .get(&DataKey::MerkleRoot).unwrap();
        if public_inputs.merkle_root != stored_root {
            panic!("Merkle root mismatch");
        }

        // Check 3: replay protection — nullifier must be fresh
        let nullifier_key = DataKey::UsedNullifier(public_inputs.nullifier.clone());
        if env.storage().persistent().has(&nullifier_key) {
            panic!("Nullifier already used: replay attack blocked");
        }

        // ── Payout via XLM SAC ────────────────────────────────────────────
        let payout: i128 = env.storage().instance()
            .get(&DataKey::PayoutAmount).unwrap();
        let token_address: Address = env.storage().instance()
            .get(&DataKey::TokenAddress).unwrap();
        token::Client::new(&env, &token_address)
            .transfer(&env.current_contract_address(), &claimant, &payout);

        // ── State updates ─────────────────────────────────────────────────
        env.storage().persistent().set(&nullifier_key, &true);
        // Extend nullifier TTL so replay protection survives archival (~30 days)
        env.storage().persistent().extend_ttl(&nullifier_key, 518_400, 518_400);

        let count: u32 = env.storage().instance()
            .get(&DataKey::ClaimedCount).unwrap_or(0);
        env.storage().instance().set(&DataKey::ClaimedCount, &(count + 1));
        // Refresh instance storage TTL on every claim
        env.storage().instance().extend_ttl(518_400, 518_400);

        env.events().publish(
            (symbol_short!("claim"), symbol_short!("paid")),
            ClaimEvent {
                disbursement_id: public_inputs.disbursement_id,
                nullifier: public_inputs.nullifier,
                claimant,
                amount: payout,
            },
        );
    }

    /// Returns live campaign stats. Escrow balance is read directly from the token SAC.
    pub fn stats(env: Env) -> CampaignStats {
        let token_address: Address = env.storage().instance()
            .get(&DataKey::TokenAddress).unwrap();
        let escrow_balance = token::Client::new(&env, &token_address)
            .balance(&env.current_contract_address());

        CampaignStats {
            disbursement_id: env.storage().instance().get(&DataKey::DisbursementId).unwrap(),
            merkle_root: env.storage().instance().get(&DataKey::MerkleRoot).unwrap(),
            payout_amount: env.storage().instance().get(&DataKey::PayoutAmount).unwrap(),
            escrow_balance,
            claimed_count: env.storage().instance().get(&DataKey::ClaimedCount).unwrap_or(0),
        }
    }

    /// Returns true if the given nullifier has already been used.
    pub fn is_nullifier_used(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage().persistent().has(&DataKey::UsedNullifier(nullifier))
    }

    /// Admin can rotate the Merkle root for a new beneficiary list.
    /// Emits a `root.updated` event containing the new root for auditor visibility.
    pub fn update_root(env: Env, new_root: BytesN<32>) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
        let old_root: BytesN<32> = env.storage().instance()
            .get(&DataKey::MerkleRoot).unwrap();
        env.storage().instance().set(&DataKey::MerkleRoot, &new_root);
        env.events().publish(
            (symbol_short!("root"), symbol_short!("updated")),
            (old_root, new_root),
        );
    }
}
