'use client';

// Client-side Groth16 proof generation (BLS12-381).
// The secret NEVER leaves this device — all computation runs in the browser via WASM.
//
// Circuit artifacts expected in /public/:
//   /circuit.wasm          — compiled AidShield circom circuit
//   /circuit_final.zkey    — Groth16 proving key (generated by setup.sh)
//
// Proof wire format (Soroban uncompressed affine):
//   pi_a: X(48) || Y(48)                                             = 96 bytes
//   pi_b: X_c1(48) || X_c0(48) || Y_c1(48) || Y_c0(48)             = 192 bytes
//   pi_c: X(48) || Y(48)                                             = 96 bytes
//   Total: 384 bytes
//
// Public inputs (BLS12-381 Fr, big-endian 32 bytes each, 128 bytes total):
//   disbursement_id | merkle_root | nullifier | claimant_address

export interface ProverInput {
  secret: string;           // 64-char hex
  merkle_path: string[];    // 8 × 64-char hex siblings
  path_indices: boolean[];  // 8 booleans (false=left, true=right)
  disbursement_id: string;  // 64-char hex
  merkle_root: string;      // 64-char hex
  claimant_address: string; // 62–64 char hex (stellarAddressToField output)
}

export interface ProverOutput {
  proof: string;        // 768-char hex = 384 bytes
  publicInputs: string; // 256-char hex = 128 bytes (disbursement_id|merkle_root|nullifier|claimant)
  nullifier: string;    // 64-char hex (BLS12-381 scalar)
  proofSize: number;    // 384
}

// BLS12-381 scalar field prime r
const BLS12_381_R =
  52435875175126190479447740508185965837690552500527637822603658699938581184513n;

// ── Poseidon BLS12-381 ──────────────────────────────────────────────────────
// Optimised Poseidon sponge matching circomlib poseidon.circom compiled for
// BLS12-381. Constants (C, S, M, P) come from poseidon_constants_opt.js; all
// arithmetic is performed mod BLS12-381 prime instead of BN254.

const fmod = (x: bigint) => ((x % BLS12_381_R) + BLS12_381_R) % BLS12_381_R;
const fadd = (a: bigint, b: bigint) => fmod(a + b);
const fmul = (a: bigint, b: bigint) => fmod(a * b);
const fpow5 = (x: bigint) => fmul(fmul(fmul(x, x), fmul(x, x)), x);

const N_ROUNDS_F_POSEIDON = 8;
const N_ROUNDS_P_POSEIDON = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68];

type PoseidonConsts = { C: bigint[]; S: bigint[]; M: bigint[][]; P: bigint[][] };
const _constCache = new Map<number, PoseidonConsts>();

async function getPoseidonConsts(t: number): Promise<PoseidonConsts> {
  if (_constCache.has(t)) return _constCache.get(t)!;
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore — internal path, not in package exports; resolved at runtime by webpack
  const mod = await import('circomlibjs/src/poseidon_constants_opt.js');
  const raw = (mod.default ?? mod) as Record<string, unknown[][]>;
  const idx = t - 2;
  const toBI = (x: unknown) => BigInt(x as string);
  const consts: PoseidonConsts = {
    C: (raw.C[idx] as unknown[]).map(toBI),
    S: (raw.S[idx] as unknown[]).map(toBI),
    M: (raw.M[idx] as unknown[][]).map((r) => r.map(toBI)),
    P: (raw.P[idx] as unknown[][]).map((r) => r.map(toBI)),
  };
  _constCache.set(t, consts);
  return consts;
}

async function poseidonBLS12381(inputs: bigint[]): Promise<bigint> {
  const t = inputs.length + 1;
  const nRoundsP = N_ROUNDS_P_POSEIDON[t - 2];
  const { C, S, M, P } = await getPoseidonConsts(t);

  let state: bigint[] = [0n, ...inputs.map(fmod)];
  for (let i = 0; i < t; i++) state[i] = fadd(state[i], C[i]);

  for (let r = 0; r < N_ROUNDS_F_POSEIDON / 2 - 1; r++) {
    state = state.map(fpow5);
    state = state.map((a, i) => fadd(a, C[(r + 1) * t + i]));
    state = state.map((_, i) => state.reduce((acc, a, j) => fadd(acc, fmul(M[j][i], a)), 0n));
  }
  state = state.map(fpow5);
  state = state.map((a, i) => fadd(a, C[(N_ROUNDS_F_POSEIDON / 2) * t + i]));
  state = state.map((_, i) => state.reduce((acc, a, j) => fadd(acc, fmul(P[j][i], a)), 0n));

  for (let r = 0; r < nRoundsP; r++) {
    state[0] = fpow5(state[0]);
    state[0] = fadd(state[0], C[(N_ROUNDS_F_POSEIDON / 2 + 1) * t + r]);
    const s0 = state.reduce((acc, a, j) => fadd(acc, fmul(S[(t * 2 - 1) * r + j], a)), 0n);
    for (let k = 1; k < t; k++) {
      state[k] = fadd(state[k], fmul(state[0], S[(t * 2 - 1) * r + t + k - 1]));
    }
    state[0] = s0;
  }

  for (let r = 0; r < N_ROUNDS_F_POSEIDON / 2 - 1; r++) {
    state = state.map(fpow5);
    state = state.map((a, i) => fadd(a, C[(N_ROUNDS_F_POSEIDON / 2 + 1) * t + nRoundsP + r * t + i]));
    state = state.map((_, i) => state.reduce((acc, a, j) => fadd(acc, fmul(M[j][i], a)), 0n));
  }
  state = state.map(fpow5);
  state = state.map((_, i) => state.reduce((acc, a, j) => fadd(acc, fmul(M[j][i], a)), 0n));

  return state[0];
}

// ── Encoding helpers ────────────────────────────────────────────────────────

function bigintToBytes48(n: bigint): Uint8Array {
  const hex = n.toString(16).padStart(96, '0');
  return Uint8Array.from(Buffer.from(hex, 'hex'));
}

function bigintToBytes32(n: bigint): Uint8Array {
  const hex = n.toString(16).padStart(64, '0');
  return Uint8Array.from(Buffer.from(hex, 'hex'));
}

function hexToFieldElement(hex: string): bigint {
  return BigInt('0x' + hex.padStart(64, '0'));
}

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('hex');
}

// Serialize snarkjs Groth16 proof to Soroban uncompressed affine bytes (384 bytes)
function serializeProof(proof: {
  pi_a: string[];
  pi_b: string[][];
  pi_c: string[];
}): Uint8Array {
  const out = new Uint8Array(384);

  // G1: X(48) || Y(48)
  const g1Bytes = (pt: string[]) => {
    const b = new Uint8Array(96);
    b.set(bigintToBytes48(BigInt(pt[0])), 0);
    b.set(bigintToBytes48(BigInt(pt[1])), 48);
    return b;
  };

  // G2: X_c1(48) || X_c0(48) || Y_c1(48) || Y_c0(48)
  // snarkjs ffjavascript: pi_b[0] = [x_c0, x_c1], pi_b[1] = [y_c0, y_c1]
  const g2Bytes = (pt: string[][]) => {
    const b = new Uint8Array(192);
    b.set(bigintToBytes48(BigInt(pt[0][1])), 0);   // X_c1
    b.set(bigintToBytes48(BigInt(pt[0][0])), 48);  // X_c0
    b.set(bigintToBytes48(BigInt(pt[1][1])), 96);  // Y_c1
    b.set(bigintToBytes48(BigInt(pt[1][0])), 144); // Y_c0
    return b;
  };

  out.set(g1Bytes(proof.pi_a), 0);
  out.set(g2Bytes(proof.pi_b), 96);
  out.set(g1Bytes(proof.pi_c), 288);
  return out;
}

// ── Main prover ─────────────────────────────────────────────────────────────

export async function generateProof(
  input: ProverInput,
  onProgress?: (msg: string) => void,
): Promise<ProverOutput> {
  const log = onProgress ?? (() => {});

  // Convert inputs to BLS12-381 field elements
  const secret = hexToFieldElement(input.secret);
  const disbursementId = hexToFieldElement(input.disbursement_id);
  const merkleRoot = hexToFieldElement(input.merkle_root);
  const claimantAddr = hexToFieldElement(input.claimant_address.padStart(64, '0'));

  log('Computing Poseidon nullifier (BLS12-381)…');
  const nullifier = await poseidonBLS12381([secret, disbursementId, claimantAddr, 1n]);
  const nullifierHex = nullifier.toString(16).padStart(64, '0');

  log('Loading Groth16 circuit artifacts…');
  // Circuit inputs matching AidShieldMembership(8) signal names
  const circuitInput = {
    secret: secret.toString(),
    path_elements: input.merkle_path.map((h) => hexToFieldElement(h).toString()),
    path_indices: input.path_indices.map((b) => (b ? '1' : '0')),
    disbursement_id: disbursementId.toString(),
    merkle_root: merkleRoot.toString(),
    nullifier: nullifier.toString(),
    claimant_address: claimantAddr.toString(),
  };

  log('Generating Groth16 proof (BLS12-381 pairing, ~15 s)…');
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore — snarkjs has no published TypeScript types
  const snarkjs = await import('snarkjs') as typeof import('snarkjs');
  const { proof, publicSignals } = (await snarkjs.groth16.fullProve(
    circuitInput,
    '/circuit.wasm',
    '/circuit_final.zkey',
  )) as {
    proof: { pi_a: string[]; pi_b: string[][]; pi_c: string[] };
    publicSignals: string[];
  };

  log('Serialising proof to Soroban wire format…');
  const proofBytes = serializeProof(proof);

  // Public inputs: disbursement_id | merkle_root | nullifier | claimant_address (128 bytes)
  // publicSignals order follows the circuit declaration: [disbursement_id, merkle_root, nullifier, claimant_address]
  const piBytes = new Uint8Array(128);
  for (let i = 0; i < 4; i++) {
    piBytes.set(bigintToBytes32(BigInt(publicSignals[i])), i * 32);
  }

  return {
    proof: toHex(proofBytes),
    publicInputs: toHex(piBytes),
    nullifier: nullifierHex,
    proofSize: proofBytes.length,
  };
}
