'use client';

// Client-side Groth16 proof generation (BLS12-381).
// The secret NEVER leaves this device — all computation runs in the browser via WASM.
//
// Circuit artifacts expected in /public/:
//   /circuit.wasm          — compiled AidShield circom circuit
//   /circuit_final.zkey    — Groth16 proving key (generated by setup.sh)
//
// Proof wire format (Soroban uncompressed affine):
//   pi_a: X(48) || Y(48)                                             = 96 bytes
//   pi_b: X_c1(48) || X_c0(48) || Y_c1(48) || Y_c0(48)             = 192 bytes
//   pi_c: X(48) || Y(48)                                             = 96 bytes
//   Total: 384 bytes
//
// Public inputs (BLS12-381 Fr, big-endian 32 bytes each, 128 bytes total):
//   disbursement_id | merkle_root | nullifier | claimant_address

export interface ProverInput {
  secret: string;           // 64-char hex
  merkle_path: string[];    // 8 × 64-char hex siblings
  path_indices: boolean[];  // 8 booleans (false=left, true=right)
  disbursement_id: string;  // 64-char hex
  merkle_root: string;      // 64-char hex
  claimant_address: string; // 62–64 char hex (stellarAddressToField output)
}

export interface ProverOutput {
  proof: string;        // 768-char hex = 384 bytes
  publicInputs: string; // 256-char hex = 128 bytes (disbursement_id|merkle_root|nullifier|claimant)
  nullifier: string;    // 64-char hex (BLS12-381 scalar)
  proofSize: number;    // 384
}

// BLS12-381 scalar field prime r
const BLS12_381_R =
  52435875175126190479447740508185965837690552500527637822603658699938581184513n;

// ── Poseidon BLS12-381 ──────────────────────────────────────────────────────
// Same constant approach as poseidon_bls12381.mjs:
// Borrow the BN254 round constants from circomlibjs — they are pure numeric values
// that are also valid BLS12-381 field elements (BN254 prime < BLS12-381 prime).
// Re-run the sponge with modular arithmetic over BLS12-381 prime.

let _poseidonConstants: { C: bigint[][]; M: bigint[][][] } | null = null;

async function getPoseidonConstants() {
  if (_poseidonConstants) return _poseidonConstants;
  const { buildPoseidon } = await import('circomlibjs');
  const poseidon = await buildPoseidon();
  const F = poseidon.F;
  const toBI = (x: unknown): bigint => BigInt(F.toObject(x));
  const C: bigint[][] = poseidon.C.map((arr: unknown[]) => arr.map(toBI));
  const M: bigint[][][] = poseidon.M.map((mat: unknown[][]) =>
    mat.map((row: unknown[]) => row.map(toBI)),
  );
  _poseidonConstants = { C, M };
  return _poseidonConstants;
}

async function poseidonBLS12381(inputs: bigint[]): Promise<bigint> {
  const p = BLS12_381_R;
  const mod = (x: bigint) => ((x % p) + p) % p;
  const add = (a: bigint, b: bigint) => mod(a + b);
  const mul = (a: bigint, b: bigint) => mod(a * b);
  const pow5 = (x: bigint) => mul(mul(mul(x, x), mul(x, x)), x);

  const { C, M } = await getPoseidonConstants();
  const t = inputs.length + 1;
  const nRoundsF = 8;
  const nRoundsP = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68][t - 2];
  const cArr = C[t - 2];
  const mArr = M[t - 2];

  let state: bigint[] = [0n, ...inputs.map((x) => mod(x))];
  for (let i = 0; i < t; i++) state[i] = add(state[i], cArr[i]);

  let cntr = t;
  for (let r = 0; r < nRoundsF + nRoundsP; r++) {
    if (r < nRoundsF / 2 || r >= nRoundsF / 2 + nRoundsP) {
      for (let i = 0; i < t; i++) state[i] = pow5(state[i]);
    } else {
      state[0] = pow5(state[0]);
    }
    const ns = new Array<bigint>(t).fill(0n);
    for (let i = 0; i < t; i++)
      for (let j = 0; j < t; j++)
        ns[i] = add(ns[i], mul(mArr[i][j], state[j]));
    state = ns;
    if (r < nRoundsF + nRoundsP - 1) {
      for (let i = 0; i < t; i++) state[i] = add(state[i], cArr[cntr + i]);
      cntr += t;
    }
  }
  return state[0];
}

// ── Encoding helpers ────────────────────────────────────────────────────────

function bigintToBytes48(n: bigint): Uint8Array {
  const hex = n.toString(16).padStart(96, '0');
  return Uint8Array.from(Buffer.from(hex, 'hex'));
}

function bigintToBytes32(n: bigint): Uint8Array {
  const hex = n.toString(16).padStart(64, '0');
  return Uint8Array.from(Buffer.from(hex, 'hex'));
}

function hexToFieldElement(hex: string): bigint {
  return BigInt('0x' + hex.padStart(64, '0'));
}

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('hex');
}

// Serialize snarkjs Groth16 proof to Soroban uncompressed affine bytes (384 bytes)
function serializeProof(proof: {
  pi_a: string[];
  pi_b: string[][];
  pi_c: string[];
}): Uint8Array {
  const out = new Uint8Array(384);

  // G1: X(48) || Y(48)
  const g1Bytes = (pt: string[]) => {
    const b = new Uint8Array(96);
    b.set(bigintToBytes48(BigInt(pt[0])), 0);
    b.set(bigintToBytes48(BigInt(pt[1])), 48);
    return b;
  };

  // G2: X_c1(48) || X_c0(48) || Y_c1(48) || Y_c0(48)
  // snarkjs ffjavascript: pi_b[0] = [x_c0, x_c1], pi_b[1] = [y_c0, y_c1]
  const g2Bytes = (pt: string[][]) => {
    const b = new Uint8Array(192);
    b.set(bigintToBytes48(BigInt(pt[0][1])), 0);   // X_c1
    b.set(bigintToBytes48(BigInt(pt[0][0])), 48);  // X_c0
    b.set(bigintToBytes48(BigInt(pt[1][1])), 96);  // Y_c1
    b.set(bigintToBytes48(BigInt(pt[1][0])), 144); // Y_c0
    return b;
  };

  out.set(g1Bytes(proof.pi_a), 0);
  out.set(g2Bytes(proof.pi_b), 96);
  out.set(g1Bytes(proof.pi_c), 288);
  return out;
}

// ── Main prover ─────────────────────────────────────────────────────────────

export async function generateProof(
  input: ProverInput,
  onProgress?: (msg: string) => void,
): Promise<ProverOutput> {
  const log = onProgress ?? (() => {});

  // Convert inputs to BLS12-381 field elements
  const secret = hexToFieldElement(input.secret);
  const disbursementId = hexToFieldElement(input.disbursement_id);
  const merkleRoot = hexToFieldElement(input.merkle_root);
  const claimantAddr = hexToFieldElement(input.claimant_address.padStart(64, '0'));

  log('Computing Poseidon nullifier (BLS12-381)…');
  const nullifier = await poseidonBLS12381([secret, disbursementId, claimantAddr, 1n]);
  const nullifierHex = nullifier.toString(16).padStart(64, '0');

  log('Loading Groth16 circuit artifacts…');
  // Circuit inputs matching AidShieldMembership(8) signal names
  const circuitInput = {
    secret: secret.toString(),
    path_elements: input.merkle_path.map((h) => hexToFieldElement(h).toString()),
    path_indices: input.path_indices.map((b) => (b ? '1' : '0')),
    disbursement_id: disbursementId.toString(),
    merkle_root: merkleRoot.toString(),
    nullifier: nullifier.toString(),
    claimant_address: claimantAddr.toString(),
  };

  log('Generating Groth16 proof (BLS12-381 pairing, ~15 s)…');
  const snarkjs = await import('snarkjs');
  const { proof, publicSignals } = (await snarkjs.groth16.fullProve(
    circuitInput,
    '/circuit.wasm',
    '/circuit_final.zkey',
  )) as {
    proof: { pi_a: string[]; pi_b: string[][]; pi_c: string[] };
    publicSignals: string[];
  };

  log('Serialising proof to Soroban wire format…');
  const proofBytes = serializeProof(proof);

  // Public inputs: disbursement_id | merkle_root | nullifier | claimant_address (128 bytes)
  // publicSignals order follows the circuit declaration: [disbursement_id, merkle_root, nullifier, claimant_address]
  const piBytes = new Uint8Array(128);
  for (let i = 0; i < 4; i++) {
    piBytes.set(bigintToBytes32(BigInt(publicSignals[i])), i * 32);
  }

  return {
    proof: toHex(proofBytes),
    publicInputs: toHex(piBytes),
    nullifier: nullifierHex,
    proofSize: proofBytes.length,
  };
}
